entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false

certificatesResolvers:
  leresolver:
    acme:
      email: your@email.com
      storage: /acme.json
      httpChallenge:
        entryPoint: web
