version: '3.8'

services:
  mcp-server:
    image: yanyuit/mcp-server:v2.0.1-20250906
    container_name: mcp-server
    ports:
      - "8080:8080"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
