version: '3.8'

services:
  mcp-server:
    image: yanyuit/mcp-server:v2.0.1-20250906
    container_name: mcp-server
    ports:
      - "8080:8080"
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - gateway
    volumes:
      - ./logs:/app/logs

  db:
    image: mariadb:10.11
    container_name: mcp-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - db-data:/var/lib/mysql

  redis:
    image: redis:7.2
    container_name: mcp-cache
    restart: unless-stopped
    volumes:
      - redis-data:/data

  gateway:
    image: nginx:alpine
    container_name: mcp-gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - mcp-server

volumes:
  db-data:
  redis-data:
